### ISSUE TITLE
Fix timepicker component styling

### ISSUE THREAD

**Issue by welvin21** [rcltech/raven#18]
Since we overrode the `MuiButton`'s css styling, all `MuiButton` embedded got changed as well. 

<img width="1440" alt="Screenshot 2020-03-22 at 12 31 47 AM" src="https://user-images.githubusercontent.com/47080921/77231280-d9d3da00-6bd4-11ea-96ba-34c8557c4ee8.png">

**Comment by 98sean98** [comment]
wrap an inner layer of `ThemeProvider` to override I suppose
